package Vista;

import Controlador.Ctrl_Cliente;
import Modelo.Cliente;
import conexion.conexionBD;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class InterGestionarCliente extends javax.swing.JInternalFrame {

    public int idCliente;

    public InterGestionarCliente() {
        initComponents();
        this.setSize(new Dimension(900, 500));
        this.setTitle("Gestionar Clientes");

        this.CargarTablaCliente();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_cliente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        boton_actualizar = new javax.swing.JButton();
        boton_eliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_direccion_cliente = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_telefono_proovedor1 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_descripcion_prooducto1 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txt_telefono_proovedor2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_apellido_cliente = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_cedula_cliente = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_telefono_proovedor3 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_nombre_cliente = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_telefono_cliente = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txt_telefono_proovedor4 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txt_descripcion_prooducto3 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_telefono_proovedor5 = new javax.swing.JTextField();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre proovedor:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        setBackground(new java.awt.Color(153, 153, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ADMINISTRAR CLIENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1_cliente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 540, 250));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_actualizar.setBackground(new java.awt.Color(153, 255, 153));
        boton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_actualizar.setText("ACTUALIZAR");
        boton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(boton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, -1));

        boton_eliminar.setBackground(new java.awt.Color(255, 51, 51));
        boton_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_eliminar.setText("ELIMINAR");
        boton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(boton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 540, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Dirección:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_direccion_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccion_clienteActionPerformed(evt);
            }
        });
        jPanel3.add(txt_direccion_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Precio productor:");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_telefono_proovedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefono_proovedor1ActionPerformed(evt);
            }
        });
        jPanel7.add(txt_telefono_proovedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 190, 60));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Telefono:");
        jPanel14.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_descripcion_prooducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcion_prooducto1ActionPerformed(evt);
            }
        });
        jPanel14.add(txt_descripcion_prooducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Precio productor:");
        jPanel15.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_telefono_proovedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefono_proovedor2ActionPerformed(evt);
            }
        });
        jPanel15.add(txt_telefono_proovedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 190, 60));

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 190, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 190, 60));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Apellido");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, -1));
        jPanel6.add(txt_apellido_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 190, 60));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cédula");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_cedula_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedula_clienteActionPerformed(evt);
            }
        });
        jPanel8.add(txt_cedula_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Precio productor:");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_telefono_proovedor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefono_proovedor3ActionPerformed(evt);
            }
        });
        jPanel9.add(txt_telefono_proovedor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 190, 60));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 190, 60));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Nombre :");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        jPanel10.add(txt_nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 190, 60));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Teléfono:");
        jPanel16.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_telefono_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefono_clienteActionPerformed(evt);
            }
        });
        jPanel16.add(txt_telefono_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Precio productor:");
        jPanel17.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_telefono_proovedor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefono_proovedor4ActionPerformed(evt);
            }
        });
        jPanel17.add(txt_telefono_proovedor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 190, 60));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Telefono:");
        jPanel18.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_descripcion_prooducto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcion_prooducto3ActionPerformed(evt);
            }
        });
        jPanel18.add(txt_descripcion_prooducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Precio productor:");
        jPanel19.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_telefono_proovedor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefono_proovedor5ActionPerformed(evt);
            }
        });
        jPanel19.add(txt_telefono_proovedor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 190, 60));

        jPanel16.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 190, 60));

        getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 190, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_direccion_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccion_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccion_clienteActionPerformed

    private void boton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_actualizarActionPerformed
        if (txt_nombre_cliente.getText().isEmpty() && txt_apellido_cliente.getText().isEmpty() && txt_cedula_cliente.getText().isEmpty() && txt_telefono_cliente.getText().isEmpty() && txt_direccion_cliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa todos los campos");
        } else {
            Cliente cliente = new Cliente();
            Ctrl_Cliente controlCliente = new Ctrl_Cliente();

            cliente.setNombre(txt_nombre_cliente.getText().trim());
            cliente.setApellio(txt_apellido_cliente.getText().trim());
            cliente.setCedula(txt_cedula_cliente.getText().trim());
            cliente.setTelefono(txt_telefono_cliente.getText().trim());
            cliente.setDireccion(txt_direccion_cliente.getText().trim());

            if (controlCliente.actualizar(cliente, idCliente)) {
                JOptionPane.showMessageDialog(null, "Datos del cliente actualizados");
                this.CargarTablaCliente();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar");
            }
        }

    }//GEN-LAST:event_boton_actualizarActionPerformed

    private void boton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminarActionPerformed

        Ctrl_Cliente conCliente = new Ctrl_Cliente();
        if(idCliente==0){
            JOptionPane.showMessageDialog(null, "Seleccione un cliente");
        }else{
            if(!conCliente.eliminar(idCliente)){
                JOptionPane.showMessageDialog(null, "Cliente eliminado");
                this.CargarTablaCliente();
                this.Limpiar();
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar");
                this.Limpiar();
            }
        }
        
            
    }//GEN-LAST:event_boton_eliminarActionPerformed

    private void txt_telefono_proovedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefono_proovedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefono_proovedor1ActionPerformed

    private void txt_cedula_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedula_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedula_clienteActionPerformed

    private void txt_telefono_proovedor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefono_proovedor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefono_proovedor3ActionPerformed

    private void txt_descripcion_prooducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcion_prooducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcion_prooducto1ActionPerformed

    private void txt_telefono_proovedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefono_proovedor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefono_proovedor2ActionPerformed

    private void txt_telefono_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefono_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefono_clienteActionPerformed

    private void txt_telefono_proovedor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefono_proovedor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefono_proovedor4ActionPerformed

    private void txt_descripcion_prooducto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcion_prooducto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcion_prooducto3ActionPerformed

    private void txt_telefono_proovedor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefono_proovedor5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefono_proovedor5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_actualizar;
    private javax.swing.JButton boton_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1_cliente;
    private javax.swing.JTextField txt_apellido_cliente;
    private javax.swing.JTextField txt_cedula_cliente;
    private javax.swing.JTextField txt_descripcion_prooducto1;
    private javax.swing.JTextField txt_descripcion_prooducto3;
    private javax.swing.JTextField txt_direccion_cliente;
    private javax.swing.JTextField txt_nombre_cliente;
    private javax.swing.JTextField txt_telefono_cliente;
    private javax.swing.JTextField txt_telefono_proovedor1;
    private javax.swing.JTextField txt_telefono_proovedor2;
    private javax.swing.JTextField txt_telefono_proovedor3;
    private javax.swing.JTextField txt_telefono_proovedor4;
    private javax.swing.JTextField txt_telefono_proovedor5;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        txt_nombre_cliente.setText("");
        txt_apellido_cliente.setText("");
        txt_cedula_cliente.setText("");
        txt_telefono_cliente.setText("");
        txt_direccion_cliente.setText("");

    }

//metodo para cargar los proovedores
    //metodo para mostrar todos los cleinte registrados
    private void CargarTablaCliente() {
        Connection con = conexion.conexionBD.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select * from cliente";
        Statement st;

        try {

            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            InterGestionarCliente.jTable1_cliente = new JTable(model);
            InterGestionarCliente.jScrollPane1.setViewportView(InterGestionarCliente.jTable1_cliente);
            model.addColumn("No."); //id
            model.addColumn("nombre");
            model.addColumn("apellido");
            model.addColumn("cédula");
            model.addColumn("teléfono");
            model.addColumn("dirección");
            model.addColumn("estado");

            while (rs.next()) {

                Object fila[] = new Object[7];
                for (int i = 0; i < 7; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            con.close();

        } catch (SQLException e) {
            System.out.println("Error la llenar la tabla de cliente");
        }

        jTable1_cliente.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable1_cliente.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idCliente = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosClienteSeleccionado(idCliente);

                }
            }

        });

    }

    private void EnviarDatosClienteSeleccionado(int idCliente) {
        try {
            Connection con = conexionBD.conectar();
            PreparedStatement pst = con.prepareStatement("select * from `cliente`where `id_cliente`='" + idCliente + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_nombre_cliente.setText(rs.getString("nombre_cliente"));
                txt_apellido_cliente.setText(rs.getString("apellido_cliente"));
                txt_cedula_cliente.setText(rs.getString("cedula_cliente"));
                txt_telefono_cliente.setText(rs.getString("telefono_cliente"));
                txt_direccion_cliente.setText(rs.getString("direccion_cliente"));

            }
            con.close();

        } catch (SQLException e) {
            System.out.println("Error al seleccionar cliente");
        }
    }

}
