package Vista;

import Controlador.Ctrl_Productos;
import Controlador.Ctrl_Proovedores;
import Modelo.Productos;
import Modelo.Proovedores;
import conexion.conexionBD;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class InterGestionarProductos extends javax.swing.JInternalFrame {

    public int idProducto;
    int obtenerProovedorCombo = 0;
    int obtenerIdProovedoresCombo = 0;

    public InterGestionarProductos() {
        initComponents();
        this.setSize(new Dimension(900, 500));
        this.setTitle("Gestionar Productos");

        this.CargarTablaProducto();
        this.CargarComboProovedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_producto = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        boton_actualizar = new javax.swing.JButton();
        boton_eliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_descripcion_prooducto = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_telefono_proovedor1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_iva_producto1 = new javax.swing.JTextField();
        jComboBox2_proovedor = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_cantidad_producto = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_precio_producto = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_telefono_proovedor3 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_nombre_producto = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_iva_producto3 = new javax.swing.JTextField();
        jComboBox1_IVA = new javax.swing.JComboBox<>();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre proovedor:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        setBackground(new java.awt.Color(153, 153, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ADMINISTAR PRODUCTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1_producto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 540, 250));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_actualizar.setBackground(new java.awt.Color(153, 255, 153));
        boton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_actualizar.setText("ACTUALIZAR");
        boton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(boton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, -1));

        boton_eliminar.setBackground(new java.awt.Color(255, 51, 51));
        boton_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_eliminar.setText("ELIMINAR");
        boton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(boton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 540, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Descripción:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_descripcion_prooducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcion_prooductoActionPerformed(evt);
            }
        });
        jPanel3.add(txt_descripcion_prooducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Precio productor:");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_telefono_proovedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefono_proovedor1ActionPerformed(evt);
            }
        });
        jPanel7.add(txt_telefono_proovedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 190, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 190, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Proovedor:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("IVA:");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        jPanel11.add(txt_iva_producto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 190, 60));

        jComboBox2_proovedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un proovedor:", " " }));
        jPanel5.add(jComboBox2_proovedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 190, 60));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Cantidad:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, -1));
        jPanel6.add(txt_cantidad_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 190, 60));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Precio producto:");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_precio_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precio_productoActionPerformed(evt);
            }
        });
        jPanel8.add(txt_precio_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Precio productor:");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_telefono_proovedor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefono_proovedor3ActionPerformed(evt);
            }
        });
        jPanel9.add(txt_telefono_proovedor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 190, 60));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 190, 60));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Nombre productos:");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        jPanel10.add(txt_nombre_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 190, 60));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("IVA:");
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("IVA:");
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        jPanel13.add(txt_iva_producto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 190, 60));

        jComboBox1_IVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona IVA:", "No aplica" }));
        jComboBox1_IVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_IVAActionPerformed(evt);
            }
        });
        jPanel12.add(jComboBox1_IVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 190, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_descripcion_prooductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcion_prooductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcion_prooductoActionPerformed

    private void boton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_actualizarActionPerformed
       
        Productos productos = new Productos();
        Ctrl_Productos controlProductos = new Ctrl_Productos();
        String iva = "";
        String proovedores = "";
        iva = jComboBox1_IVA.getSelectedItem().toString().trim();
        proovedores = jComboBox2_proovedor.getSelectedItem().toString().trim();

        //validar campos
        if (txt_nombre_producto.getText().isEmpty() || txt_precio_producto.getText().isEmpty()|| txt_cantidad_producto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "complete todos los campos");

        } else {
            //consulta si el producto existe
                if (iva.equalsIgnoreCase("Selecciona IVA:")) {
                    JOptionPane.showMessageDialog(null, "Selecciona IVA:");
                } else {
                    if (proovedores.equalsIgnoreCase("Seleccione un proovedor:")) {
                        JOptionPane.showMessageDialog(null, "Seleccione un proovedor:");
                    } else {
                        try {
                            productos.setNombreProducto(txt_nombre_producto.getText().trim());
                            productos.setCantidadProducto(Integer.parseInt(txt_cantidad_producto.getText().trim()));
                            String precioTXT = "";
                            double Precio = 0.0;
                            precioTXT = txt_precio_producto.getText().trim();
                            boolean aux = false;
                            //si el usuario ingresa ,(como) como punto decial, lo tranformamos
                            for (int i = 0; i < precioTXT.length(); i++) {
                                if (precioTXT.charAt(i) == ',') {
                                    String precioNuevo = precioTXT.replace(",", ".");
                                    Precio = Double.parseDouble(precioNuevo);
                                    aux = true;
                                }
                            }

                            //evaluar condicion
                            if (aux == true) {
                                productos.setPrecioProducto(Precio);
                            } else {
                                Precio = Double.parseDouble(precioTXT);
                                productos.setPrecioProducto(Precio);
                            }

                            productos.setDescripcionProducto(txt_descripcion_prooducto.getText().trim());
                            //porcentaje IVA
                            if (iva.equalsIgnoreCase("No aplica")) {
                                productos.setPorcentajeIVA(0);
                            } else if (iva.equalsIgnoreCase("16%")) {
                                productos.setPorcentajeIVA(0);
                            }
                            //idproovedor-cargar metodo que obtiene el id de proovedor
                            this.IdProovedores();
                            productos.setIdProovedor(obtenerIdProovedoresCombo);
                            productos.setEstado(1);

                            if (controlProductos.actualizar(productos,idProducto)) {
                                JOptionPane.showMessageDialog(null, "Registro actualizado");
                                this.CargarComboProovedores();
                                this.CargarTablaProducto();
                               
                                this.jComboBox1_IVA.setSelectedItem("Selecciona IVA:");
                                this.Limpiar();
                            } else {
                                 JOptionPane.showMessageDialog(null, "error al actualizar");                   
                            }

                        } catch (HeadlessException | NumberFormatException e) {
                            System.err.println("Error en:"+e);
                        }
                    }
                }
        }
        
      //}
    

    }//GEN-LAST:event_boton_actualizarActionPerformed

    private void boton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminarActionPerformed
         Ctrl_Productos controlProductos = new Ctrl_Productos();
        
        if(idProducto==0){
            JOptionPane.showMessageDialog(null, "Seleccione un producto"); 
        }else{
            if(!controlProductos.eliminar(idProducto)){
               JOptionPane.showMessageDialog(null, "Producto eliminado"); 
               this.CargarTablaProducto();
               this.CargarComboProovedores();
               this.Limpiar();
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar producto"); 
            }
        }
    }//GEN-LAST:event_boton_eliminarActionPerformed

    private void txt_telefono_proovedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefono_proovedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefono_proovedor1ActionPerformed

    private void txt_precio_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precio_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precio_productoActionPerformed

    private void txt_telefono_proovedor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefono_proovedor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefono_proovedor3ActionPerformed

    private void jComboBox1_IVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_IVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_IVAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_actualizar;
    private javax.swing.JButton boton_eliminar;
    private javax.swing.JComboBox<String> jComboBox1_IVA;
    private javax.swing.JComboBox<String> jComboBox2_proovedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1_producto;
    private javax.swing.JTextField txt_cantidad_producto;
    private javax.swing.JTextField txt_descripcion_prooducto;
    private javax.swing.JTextField txt_iva_producto1;
    private javax.swing.JTextField txt_iva_producto3;
    private javax.swing.JTextField txt_nombre_producto;
    private javax.swing.JTextField txt_precio_producto;
    private javax.swing.JTextField txt_telefono_proovedor1;
    private javax.swing.JTextField txt_telefono_proovedor3;
    // End of variables declaration//GEN-END:variables

   
private void Limpiar(){
    txt_nombre_producto.setText("");
    txt_cantidad_producto.setText("");
    txt_precio_producto.setText("");
    txt_descripcion_prooducto.setText("");
    jComboBox1_IVA.setSelectedItem(("Seleccione IVA:"));
    jComboBox2_proovedor.setSelectedItem("Seleccione un proovedor:");
 
}    


//metodo para cargar los proovedores
    private void CargarComboProovedores() {
        Connection cn = conexionBD.conectar();
        String sql = "select * from `proovedores`";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox2_proovedor.removeAllItems();
            jComboBox2_proovedor.addItem("Seleccione un proovedor:");
            while (rs.next()) {
                jComboBox2_proovedor.addItem(rs.getString("nombre_proovedor"));
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al cargar proovedores");
        }
    }

    //metodo para mostrar todos los productos registrados
    String nombreProovedor = "";
    double precio = 0.0;
    int porcentajeIva = 0;
    double IVA = 0;

    private void CargarTablaProducto() {
        Connection con = conexion.conexionBD.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select p.id_producto,p.nombre_producto,p.cantidad,p.precio_producto,p.descripcion_producto,p.porcentaje_iva,c.nombre_proovedor,p.estado FROM productos AS p, proovedores AS c WHERE p.id_proovedor = c.id_proovedor;";
        Statement st;

        try {

            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            InterGestionarProductos.jTable1_producto = new JTable(model);
            InterGestionarProductos.jScrollPane1.setViewportView(InterGestionarProductos.jTable1_producto);
            model.addColumn("No."); //id
            model.addColumn("nombre");
            model.addColumn("cantidad");
            model.addColumn("Precio");
            model.addColumn("descripcion");
            model.addColumn("Iva");
            model.addColumn("proovedor");
            model.addColumn("estado");

            while (rs.next()) {
                precio = rs.getDouble("precio_producto");
                porcentajeIva = rs.getInt("porcentaje_iva");

                Object fila[] = new Object[8];
                for (int i = 0; i < 8; i++) {
                    if (i == 5) {
                        this.calcularIva(precio, porcentajeIva); //metodo
                        fila[i] = IVA;
                        rs.getObject(i + 1);
                    } else {
                        fila[i] = rs.getObject(i + 1);
                    }
                }
                model.addRow(fila);
            }
            con.close();

        } catch (SQLException e) {
            System.out.println("Error la llenar la tabla de productos");
        }

        jTable1_producto.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable1_producto.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idProducto = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosProductoSeleccionado(idProducto);

                }
            }

        });

    }

    //metodo para calcular iva
    private double calcularIva(double precio, int iva) {
        int p_iva = iva;
        switch (p_iva) {
            case 0:
                IVA = 0.0;
                break;
            case 16:
                IVA = precio * 0.16;
                break;
            default:
                break;
        }
        //redondear decimales
        IVA = (double) Math.round(IVA * 100) / 100;
        return IVA;
    }

    private void EnviarDatosProductoSeleccionado(int idProducto) {
        try {
            Connection con = conexionBD.conectar();
            PreparedStatement pst = con.prepareStatement("select * from `productos`where `id_producto`='" + idProducto + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_nombre_producto.setText(rs.getString("nombre_producto"));
                txt_cantidad_producto.setText(rs.getString("cantidad"));
                txt_precio_producto.setText(rs.getString("precio_producto"));
                txt_descripcion_prooducto.setText(rs.getString("descripcion_producto"));
                int iva = rs.getInt("porcentaje_iva");
                
                switch (iva) {
            case 0:
                jComboBox1_IVA.setSelectedItem("No aplica");
                break;
            case 16:
                jComboBox1_IVA.setSelectedItem("16%");
                break;
            default:
                jComboBox1_IVA.setSelectedItem("Seleccione IVA:");
                break;
        }
                int idProove = rs.getInt("id_proovedor");
                jComboBox2_proovedor.setSelectedItem(relacionarProovedores(idProove));
            }
            con.close();

        } catch (SQLException e) {
            System.out.println("Error al seleccionar producto");
        }
    }
    
    //metodo para relacionar proovedores
    
    private String relacionarProovedores(int idProovedores){
      
        Connection cn = conexion.conexionBD.conectar();
        String sql = "select `nombre_proovedor` from `proovedores` where `id_proovedor` = '"+idProovedores+"'";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
           
            while (rs.next()) {
             nombreProovedor = rs.getString("nombre_proovedor");
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al obtener  el id del proovedores");
        }
        return nombreProovedor;
    }
        
    private int IdProovedores() {
        String sql = "select * from `proovedores` where `nombre_proovedor` = '" + this.jComboBox2_proovedor.getSelectedItem() + "'";
        Statement st;
        try {
            Connection cn = conexion.conexionBD.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                obtenerIdProovedoresCombo = rs.getInt("id_proovedor");
            }
        } catch (SQLException e) {
            System.out.println("error al obtener id_proovedor");
        }
        return obtenerIdProovedoresCombo;
    }
}
